### ISSUE TITLE
remove score from query annotation in match interface

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#486]
**Current Behavior**
`/src/pages/match/QueryAnnotationsTable.jsx` currently has a column indicating the individual's score. When talking about the query annotation, having a "score" is counter-intuitive and disruptive to the interface.
1. navigate to sighting
2. click match results
3. observe query table on match results page

**Desired Behavior**
We just need to drop the column entirely:
![image](https://github.com/WildMeOrg/codex-frontend/assets/62726866/abf21059-39e6-4eed-9a18-d43b4222df8c)

**Comment by martinyis** [comment]
Hey, can I work on that issue?

**Comment by TanyaStere42** [comment]
@martinyis we seem to already have a PR in for it? I am just getting our projects set up for others to contribute, so this is a little messy at the moment. I suspect I'll have a good answer on Tuesday (and an alternative ticket if necessary!)
