### ISSUE TITLE
My settings and privacy page locks up Chrome and Firefox

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#516]
**Expected Behavior**
Page doesn't lock

**Current Behavior**
Reproducible in Chome and Firefox from this page: https://qa.dyn.wildme.io/settings
unmounted components in preferences page cause lag and claim to be indicative of a react memory leak

![Image](https://user-images.githubusercontent.com/62726866/255717108-e9f765b3-91f6-4e94-bc21-92acda129f53.png)

**Comment by erinz2020** [comment]
this error message can be seen at several places, all caused by the same function useFetch which is a low-level query hook. in this PR we are returning the statusCode directly instead of updating the state when component in unmounted.

**Comment by TanyaStere42** [comment]
QA verified:

- [ ] settings page does not display the error message
