### ISSUE TITLE
performance issue blocks report sighting on firefox

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#517]
**Expected Behavior**
User can submit a sighting on Firefox

**Current Behavior**
For some users, a series of 401 errors locks up the reporting page on firefox once you get past image submission stage. Suspected to be a performance issue

![Image](https://user-images.githubusercontent.com/62726866/255719545-d4269e6a-b605-462f-8692-0e8e2f45625a.png)

**Comment by TanyaStere42** [comment]
@erinz2020 indicated that the unmounted component issues is something she's seen elsewhere; will address as part of this ticket too

**Comment by erinz2020** [comment]
the 401 error is because user was not logged in, but there **is** a performance issue on this page which can be fixed by this PR.

**Comment by TanyaStere42** [comment]
- [ ] verify through submission while signed in
- [ ] verify through submission while not signed in (401 error is correct)
