### ISSUE TITLE
Autogenerate names/Codex ID - Codex ID on merge individual page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#525]
Context: arguments about names are a significant reason against collaboration within biology. People want to maintain the specific name they leverage in their personal catalogue.

By providing an automatically generated name that is associated with Codex specifically, we can promote Codex as a collaboration tool, as well as a catalogue solution, by providing a workspace with common shared nomenclature that does not threaten the name spaces used in individual catalogues.

## Resources

![Image](https://user-images.githubusercontent.com/62726866/255754851-0a627740-10b5-4351-8642-88ab0b585351.png)

[Final design](https://www.figma.com/file/CQlIlIp73EjmGKANvWzoIR/Codex%3A-Autogenerate-names?type=design&node-id=259-16118&mode=design&t=lL6As7KZvdqzLDeh-0)

### User Story

- As a user on the merge individual page, I see a dropdown labeled Codex IDs.
- As a user on the merge individual page, I am required to select between the Codex IDs before I can submit the ID.

**Comment by naknomum** [comment]
see [comment on houston](https://github.com/WildMeOrg/houston/issues/880#issuecomment-1652695557) regarding backend behavior when merged individuals do not have same species.

**Comment by TanyaStere42** [comment]
- [ ]     As a user on the merge individual page, I see a dropdown labeled Codex IDs.
- [ ]     As a user on the merge individual page, I am required to select between the Codex IDs before I can submit the ID.
