### ISSUE TITLE
change log: page and table

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#533]
By giving admins and support access to a table of the changes that have taken place in the platform, we are enabling them to see patterns and problems that may improve troubleshooting and head off development and support issues

## Resources
Final design: https://www.figma.com/file/9kvaU99j6Q5XjzSYTyWmtZ/Change-Log?node-id=124-448&t=3hFNSNDVGWvYqyPo-0

![Image](https://user-images.githubusercontent.com/62726866/257335608-9904e86f-874c-476d-a48f-e0462bcb0c23.png)

## Technical notes

- we are not making modifications to the log APIs as part of this feature. This feature is entirely about getting users access to the logs without having to leverage developer tools

## User Stories

- [x]  As an administrator on the change log page, I can see a paginated list of all actions that have taken place on the platform

## QA

- [x]  Verify the change log page is populated with a table that lists messages of what has happened in the platform
- [x]  change a user’s name. verify the change shows in the table
- [x]  create a sighting. verify it shows in the table
- [x]  perform matching. verify it shows in the table
- [x]  create an individual. verify it shows in the table
- [x]  create a collaboration. verify it shows in the table

**Comment by TanyaStere42** [comment]
table display issue: can be worked around by copying text and pasting into an external text editor, so believe it's just a text-wrap issue


![Image](https://github.com/WildMeOrg/codex-frontend/assets/62726866/53b64c45-767d-4b80-8b46-311e047dedac)

**Comment by erinz2020** [comment]
there is a scroll bar under the table, slide it to the right all the content can be displayed. but this is ugly, I'll make it wrap when overflow. going to push a patch later.

![1694114510305](https://github.com/WildMeOrg/codex-frontend/assets/99415659/e96bf799-2278-4e58-9ce7-f85c3a4ad14f)

**Comment by TanyaStere42** [comment]
component issue; closing
