### ISSUE TITLE
individual search - last region location in table

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#562]
## User story
As a researcher on the individual search table, I can see an individual's last region (the region of the most recent sighting associated with the individual)
- Last region should display immediately after last seen
- Column name: Last region

### Technical notes
table options are set up here: `/src/models/individual/useIndividualSearchSchemas.js`

Use the same logic as "last seen" column to determine the most recent sighting. will keep results consistently pointing at the same thing
`'LAST_SIGHTING_DATE_RANGE'`

Dependency on https://github.com/WildMeOrg/houston/issues/907

**Comment by goddesswarship** [comment]
QA notes: Last Seen and Last Region fields correctly show up in an Individual search and correctly correspond to an individual's most recently reported date and location.
