### ISSUE TITLE
individual search - last freeform location in table

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#563]
User story

As a researcher on the individual search table, I can see an individual's last freeform location (the freeform location of the most recent sighting associated with the individual)

    Last freeform location should display immediately after last seen
    Column name: Last freeform

Technical notes

table options are set up here: /src/models/individual/useIndividualSearchSchemas.js

Use the same logic as "last seen" column to determine the most recent sighting. will keep results consistently pointing at the same thing
'LAST_SIGHTING_DATE_RANGE'

Dependency on https://github.com/WildMeOrg/houston/issues/908

**Comment by goddesswarship** [comment]
QA notes: I verified that the Freeform Location displayed in the Individual search results corresponds to the Freeform Location Metadata in the individual's most recent Sighting.
