### ISSUE TITLE
user's data page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#609]
## Context
Users are not currently able to look their all of their data without leveraging the search function. As the majority of users leverage bulk import, this blocks users from accessing their most recent uploaded data and can stop users from tracking their place in their processed data.

## User Story
- As a Codex user in the platform, I can access my home data view from the header menu
- As a codex user on my data page, I can select between several preset data views
    - my sightings (includes pending and sightings)
    - my unapproved sightings (includes pending and sightings, filtered to exclude approved and unidentifiable sightings)
- As a Codex user on any view, I can access the full list of my data through paginated tables

## Technical Notes
Sighting and Pending sighting tables: state, location, date, number of annotations, number of animals, and link to sighting

## Design

![Image](https://github.com/WildMeOrg/codex-frontend/assets/62726866/9a751ad0-e387-4a81-ad80-2b83b2716f3e)

Note: typo in design on second frame. It is "Unapproved sightings" not "approved"

**Comment by TanyaStere42** [comment]
Emergent requirement for backend: need API for number of annotations and number of animals on AGS (pending sightings)
Assigned to @naknomum for backend work

**Comment by TanyaStere42** [comment]
cutting "my individuals" table for now. requires a direct API call which will need to be addressed separately.

**Comment by naknomum** [comment]
> Emergent requirement for backend: need API for number of annotations and number of animals on AGS (pending sightings) Assigned to @naknomum for backend work

also needed: `match_state` to be returned from _search results_.

**Comment by TanyaStere42** [comment]
Reopened - QA discovered designs did not match feature spec. Page structure needs to be updated
