### ISSUE TITLE
open sightings in new tab from individual's sighting table

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#618]
## Context
When viewing related pages, such as an individual and the related sightings, there is a user expectation of being able to access all pages and move between them. As such, having the page open in a new tab would speed up user's workflow.

## User Story
As a researcher on an individual page, when I click on the navigation button on the encounter table, the page opens in a new tab.

## Technical Notes
Table appears on Page: `src/pages/individual/Individual.jsx`
change target:_self to target :_blank

## QA

- [ ] navigate to individual page
- [ ] click navigation button on encounter table. page opens in new tab
- [ ] right click > menu opens (current function)
- [ ] middle click opens in new tab (current function)

https://community.wildme.org/t/seal-codex-opening-sightings-from-individual-page/1800

**Comment by goddesswarship** [comment]
Marking as not-planned due to Seal Codex having been already migrated to Seal Wildbook.
